# Site settings
title:          YiMing's Studio
description:    "生命在于折腾"
url:            "https://namelesstudio.github.io"

# Author
author:
  name:         YiMing
  url:          http://namelesstudio.github.io
  email:        thebeautiful@163.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed


# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
paginate_path: /page/:num


#googleAnaly, your id link UA-12345678-X
googleAnaly:
  config: true
  id: UA-80213062-1

busuanzi_enabled: true
